# Generated by Django 4.2.5 on 2023-11-09 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='start_time',
            field=models.CharField(verbose_name='Время начала рассылки'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='stop_time',
            field=models.CharField(verbose_name='Время окончания рассылки'),
        ),
    ]
