# Generated by Django 4.2.5 on 2023-11-04 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateField(verbose_name='Время рассылки')),
                ('period', models.CharField(max_length=100, verbose_name=' Периодичность рассылки')),
                ('status', models.CharField(default='created', max_length=20, verbose_name='Статус рассылки')),
            ],
            options={
                'verbose_name': 'рассылка',
                'verbose_name_plural': 'рассылки',
            },
        ),
    ]
