# Generated by Django 4.2.5 on 2023-11-10 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_app', '0002_alter_newsletter_start_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='last_time',
            field=models.CharField(blank=True, null=True, verbose_name='Время последней рассылки'),
        ),
    ]
