# Generated by Django 4.2.5 on 2023-11-04 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_app', '0004_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mailing_app.text', verbose_name='Текст рассылки'),
        ),
    ]
