# Generated by Django 4.2.5 on 2023-11-23 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='temp',
            field=models.IntegerField(default=1, verbose_name='test'),
        ),
    ]
