# Generated by Django 4.2.5 on 2023-11-23 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_temp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='temp',
        ),
    ]
