# Generated by Django 4.2.5 on 2023-10-03 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_category_options_category_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.DateField(default='2023-10-03', verbose_name='Дата создания'),
            preserve_default=False,
        ),
    ]
