# Generated by Django 4.2.5 on 2023-10-29 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_remove_post_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='active_version',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Версия'),
        ),
    ]
