# Generated by Django 4.2.5 on 2023-11-23 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_product_active_version'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
